services:
  app:
    container_name: 'sub_service_app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: sub_service_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sub_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: