DO
$$
    BEGIN
        IF NOT EXISTS (SELECT
                       FROM pg_database
                       WHERE datname = 'sub_service_db') THEN
            CREATE DATABASE sub_service_db;
        END IF;
    END
$$;

\connect sub_service_db

create table if not exists users
(
    id       int primary key generated by default as identity,
    login    varchar(64)                      not null unique,
    password varchar(64) check (char_length(password) > 5) not null
);

create table if not exists sub_types
(
    id int primary key generated by default as identity,
    name varchar(32) unique
);

create table if not exists subscriptions
(
    id int primary key generated by default as identity,
    owner_id int references users(id),
    sub_type_id int references sub_types(id)
);


create table if not exists roles
(
    id   int primary key generated by default as identity,
    name varchar(32)
);

create table if not exists users_and_roles
(
    user_id int references users(id),
    role_id int references roles(id),
    primary key (user_id, role_id)
);

-- Вставка тестовых пользователей.
insert into users (login, password) values ('admin', '$2a$10$/4zJf0iO66gD2EKmB5Zuh.aMwaZs0CRfl81Uag7fUDJ8WgLecYDj6'); -- user11
insert into users (login, password) values ('user1', '$2a$10$/4zJf0iO66gD2EKmB5Zuh.aMwaZs0CRfl81Uag7fUDJ8WgLecYDj6'); -- user11
insert into users (login, password) values ('user2', '$2a$10$kZuHqmfrssDbTpXyPU4Kg.8ng300oR2qp0ddcv0Bm2cGQI6OdYsSG'); -- user22
insert into users (login, password) values ('user3', '$2a$10$4D6CUDJeDgxNlEGJqURbLegdjPen3cUu/2wm7sbtjDOacXHqFMnFC'); -- user33
insert into users (login, password) values ('user4', '$2a$10$aQSgOysqC0na.IoLxFlpEOYkoUFfcvgniN5DjRjdkHS/d4JymGEs2'); -- user44
insert into users (login, password) values ('user5', '$2a$10$NNm6aU5ftx46jeF5Z842XuTR7rx6TuJ64fJyrdFNFJm/OxFw.4FCq'); -- user55
insert into users (login, password) values ('user6', '$2a$10$7Kbhy9C.g1tqFIg0uGTNrOB3TbI7h5/.mxMxJp8aQkoaEg/jeOFLe'); -- user66
insert into users (login, password) values ('user7', '$2a$10$MzSEjcMegowmjh73KFGUZu3NBUecwxeXxDtX.uDF3mSQ/J5uxw71i'); -- user77
insert into users (login, password) values ('user8', '$2a$10$einTiJc.jNXezDMERHaIpO8uic9t7xZx/sNJU2MpXrlzm0QA3tGqu'); -- user88
insert into users (login, password) values ('user9', '$2a$10$bZA06oZJMY6vZCk72rUrzuKMPxB1DPrgF09unFa5wCI1/XjHWwJaG'); -- user99
insert into users (login, password) values ('user10', '$2a$10$dj9i/aolL1lrQTwqmv.TGeLDfbTv9Du868Bgq3Vj87reOsoS1JKnK'); -- user100

-- Вставка базовых ролей.
insert into roles (name) values ('ROLE_USER');
insert into roles (name) values ('ROLE_ADMIN');

-- Вставка типов подписок

insert into sub_types(name) values ('VK MUSIC');
insert into sub_types(name) values ('DOTA PLUS');
insert into sub_types(name) values ('NETFLIX');
insert into sub_types(name) values ('YANDEX MUSIC');
insert into sub_types(name) values ('MICROSOFT XBOX');
insert into sub_types(name) values ('PATRION');
insert into sub_types(name) values ('IWI CINEMA');
insert into sub_types(name) values ('SPOTIFY');


-- Вставка тестовых подписок.
insert into subscriptions(owner_id, sub_type_id) values (1, 1);
insert into subscriptions(owner_id, sub_type_id) values (1, 2);
insert into subscriptions(owner_id, sub_type_id) values (2, 1);
insert into subscriptions(owner_id, sub_type_id) values (2, 2);
insert into subscriptions(owner_id, sub_type_id) values (3, 1);
insert into subscriptions(owner_id, sub_type_id) values (3, 2);
insert into subscriptions(owner_id, sub_type_id) values (4, 1);
insert into subscriptions(owner_id, sub_type_id) values (4, 2);
insert into subscriptions(owner_id, sub_type_id) values (4, 2);
insert into subscriptions(owner_id, sub_type_id) values (5, 3);
insert into subscriptions(owner_id, sub_type_id) values (6, 4);
insert into subscriptions(owner_id, sub_type_id) values (7, 5);
insert into subscriptions(owner_id, sub_type_id) values (8, 6);
insert into subscriptions(owner_id, sub_type_id) values (9, 7);
insert into subscriptions(owner_id, sub_type_id) values (10, 8);

-- Вставка соответствия ролей к пользователям.
insert into users_and_roles(user_id, role_id) values (1, 2);
insert into users_and_roles(user_id, role_id) values (2, 1);
insert into users_and_roles(user_id, role_id) values (3, 1);
insert into users_and_roles(user_id, role_id) values (4, 1);
insert into users_and_roles(user_id, role_id) values (5, 1);
insert into users_and_roles(user_id, role_id) values (6, 1);
insert into users_and_roles(user_id, role_id) values (7, 1);
insert into users_and_roles(user_id, role_id) values (8, 1);
insert into users_and_roles(user_id, role_id) values (9, 1);
insert into users_and_roles(user_id, role_id) values (10, 1);
insert into users_and_roles(user_id, role_id) values (11, 1);








